name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"   # Every 12 hours (recommended format)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
